name: flutter_quill
description: One client and affiliated collaborator of Flutter Quill is Bullet Journal App.
version: 1.0.0-dev.2
#author: bulletjournal
homepage: https://bulletjournal.us/home/index.html
repository: https://github.com/singerdmx/flutter-quill.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.0.0
  collection: ^1.15.0
  tuple: ^2.0.0
  flutter_keyboard_visibility: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
